### ISSUE TITLE
[Improvment] subtitle issue

### ISSUE THREAD

**Issue by TobiAssistant** [ThibaultMontaufray/Droid-Video#3]
Encore un point sur les sous-titres : sur un de mes films où les sous-titres n'était pas intégrés à la vidéo et où je devais aller les chercher, ils sont apparus découpé sur un rectangle noir. Voir l'image bug2 que je te mets en pièce jointe avec une comparaison avec le player de base windows. Ils ont également l'air plus petits, une option pour changer la taille serait intéressante si c'est possible.
.

**Comment by ThibaultMontaufray** [comment]
TODO : integration in vlc controler of subtitles
